---
- hosts: all
  sudo: yes
  vars:
    zk:
      version: 3.4.6
      mirror: http://mirrors.supportex.net/apache
      dataDir: /var/lib/zookeeper
      installDir: "/opt"
  tasks:

  # Install Oracle JVM
  - name: Java | Ensure the Oracle JVM repository is present
    apt_repository:
      repo: ppa:webupd8team/java
      state: present
  - name: Java | Ensure the Oracle license is accepted
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: Java | Ensure Oracle Java 7 is installed
    apt:
      name: oracle-java7-installer
      state: latest

  # Download Zookeeper
  - set_fact: zk_name="zookeeper-{{zk.version}}"
  - set_fact: zk_dir="{{zk.installDir}}/{{zk_name}}"
  - name: ZooKeeper | Ensure tar {{zk_name}} is downloaded (mirror {{zk.mirror}})
    get_url:
      url: "{{zk.mirror}}/zookeeper/{{zk_name}}/{{zk_name}}.tar.gz"
      dest: "/tmp"
  - name: ZooKeeper | Ensure tar is extracted
    command: tar xzf /tmp/{{zk_name}}.tar.gz chdir="{{zk.installDir}}"

  # Config and start Zookeeper
  - name: ZooKeeper | Ensure zoo.conf is present in {{zk_dir}}/conf
    template:
      src: "templates/zk/zoo.cfg"
      dest: "{{zk_dir}}/conf"
  - name: ZooKeeper | Ensures data dir {{zk.dataDir}} exists
    file:
      path: "{{zk.dataDir}}"
      state: directory
  - name: ZooKeeper | Ensure myid is set to {{cluster_node_seq}} in {{zk.dataDir}}/myid
    template:
      src: "templates/zk/myid"
      dest: "{{zk.dataDir}}"
  - name: ZooKeeper | Ensure the service is running
    shell: "{{zk_dir}}/bin/zkServer.sh restart"
